on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go get .
      #      - name: Test with Go
      #        run: go test -json > TestResults-${{ matrix.go-version }}.json
      #      - name: Upload Go test results
      #        uses: actions/upload-artifact@v4
      #        with:
      #          name: Go-results-${{ matrix.go-version }}
      #          path: TestResults-${{ matrix.go-version }}.json


      - name: docker build and push
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login ${{secrets.OCIR_REGION_URL}} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          
          docker build -t ${{ secrets.OCIR_REGION_URL }}/test-repo/go-hello-world:latest
          docker push ${{ secrets.OCIR_REGION_URL }}/test-repo/go-hello-world:latest
